#title: Vibha Duraikkannan
#logo: docs/assets/vibha_headshot.jpg
#description: Electrical & Computer Engineering | Art | Digital Fabrication | Class of 2027
#show_downloads: true
#theme: jekyll-theme-minimal
#ABOVE IS WHERE I STARTED

title: Vibha Duraikkannan
logo: docs/assets/vibha_headshot.jpg
description: Electrical & Computer Engineering | Art | Digital Fabrication | Class of 2027

# Use GitHub Pages' Minimal theme but we’ll override layout
theme: jekyll-theme-minimal

header_pages:
  - about.md
  - projects.md

collections:
  projects:
    output: true
    permalink: /projects/:name/

permalink: pretty

