title: Vibha Duraikkannan
#logo: docs/assets/headshot_circle.png
description: Electrical & Computer Engineering | Art | Digital Fabrication | Class of 2027
#show_downloads: true
theme: jekyll-theme-minimal
