title: Vibha Duraikkannan
logo: docs/assets/vibha_headshot.jpg
description: Electrical & Computer Engineering | Art | Digital Fabrication | Class of 2027
#show_downloads: true
theme: jekyll-theme-minimal
